language: node_js

sudo: false

cache:
  apt: true
  directories:
    - node_modules

node_js: stable

branchs:
  only:
    - master
install:
  - npm install -D
  - cd ./test/smoke/template
  - npm install -D
  - cd ../../../

script:
  - npm publish